name: Project Schedule API Dev

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101

    - name: Build with dotnet
      run: dotnet build --configuration Release src/project-schedule/project-schedule.sln
    
    - name: dotnet publish
      run: |
        dotnet publish src/project-schedule/project-schedule.sln -c Release -o projectscheduleapidev

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{secrets.CREDENTIALS_NP}}

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: marine-planning
        package: ${{ github.workspace }}/projectscheduleapidev
